# vim: sw=2 ai ts=102
---
role_task: redhat
lvm: []
reboot_host: False
lvm_mounts: []
certificates: {}
add_certificates: []
extra_authorized_keys: []

router_server: "{{ groups.routers | default([]) | first | default(none) }}"
router_server_ip: "{{ 'localhost' if not router_server else hostvars[router_server].nic.ip | ipaddr('address')}}"

delegate_ip: "{{ router_server_ip if inventory_hostname in groups.proxied else 'localhost' }}"

# subscription register organization
subscription_org: "{{ change_me_subscription_org }}"
# subscription register activiation key
subscription_ak: "{{ change_me_subscription_ak }}"
# subscription repositories
subscription_repos: [rhel-7-server-rpms]
# subscription optional repos if mirror repo is defined
subscription_repos_mirror: [rhel-7-server-optional-rpms]
# needed plugins for optional mirrors
subscription_plugins: [yum-plugin-priorities.noarch]

# subscription_mirror:
#   pulp-rhel-7-server-rpms:
#     baseurl: http://registry.virt/pulp/content/dist/rhel/server/7/7Server/x86_64/os
#     sslverify: "0"
#     enabled: "1"
#     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
#     gpgcheck: "1"
subscription_mirror: {}
