# vim: sw=2 ai ts=10240
---
- name: Unconfigure Demo VMs
  hosts: demo-vms
  vars:
    vms_clean: true
  gather_facts: False
  roles: [rhel]
  tasks:
    - meta: clear_host_errors
    - meta: refresh_inventory

- name: Remove all VMs
  hosts: demo-vms
  gather_facts: false
  connection: local
  vars:
    vms_clean: true
  roles: [vms-ovirt]
