---
# sw=2 ts=102 ai

- name: grab all repos
  command: "/usr/bin/hammer --output json repository list {{ORG}} --product='{{satellite_hammer_product}}'"
  register: hammer_output
  changed_when: False
  when: repo_ids is not defined

- name: assign repos to dictionary
  set_fact:
    repo_ids: "{{ dict(json | json_query('results[*].[Name, Id]')) }}"
  when: repo_ids is not defined
  vars:
    json:
      results: "{{ hammer_output.stdout | default('[]') | from_json }}"
