# vim: sw=2 ai ts=102
---
- name: Removing VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    cluster: "{{ vm_cluster }}"
    state: absent
  tags: [ovirt]
  async: 60
  poll: 5

- name: Removing ssh key for host
  command: /usr/bin/ssh-keygen -R "{{ ansible_host }}"
  tags: [ssh]
