# vim: sw=2 ai ts=102
---
- block:
  - name: grab personal ssh key
    set_fact:
      ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: add personal ssh key to authorized_ssh_keys
    set_fact:
      authorized_ssh_keys: |
        - {{ ssh_pub_key }}
  when: authorized_ssh_keys.root|default("") == ""
  tags: [certificates]
  run_once: True

- name: Create VMs async
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    template: "{{ vm_template }}"
    cluster: "{{ vm_cluster }}"
    memory: "{{ vm_memory }}"
    memory_guaranteed: "{{ vm_memory }}"
    high_availability: false
    clone: false
    cpu_sockets: "{{ vm_cpucount }}"
    operating_system: "{{ vm_osid }}"
    type: "{{ vm_type }}"
    state: present
    nics: "{{ vm_nics }}"
    cloud_init: "{{ vm_cloud_init }}"
    wait: true
  register: vm_created
  async: 185
  poll: 5
